'use strict';

const SECTIONS = {
  listcomp_urd: {
    label: 'Listening Comprehension (Urdu)',
    group: 'Urdu',
    items: [
      'listcomp_lit1_urd',
      'listcomp_lit2_urd',
      'listcomp_lit3_urd',
      'listcomp_lit4_urd',
      'listcomp_inf1_urd',
      'listcomp_inf2_urd',
    ],
    summaryFields: ['listcomp_numcorrect_urd', 'listcomp_percorrect_urd'],
    verifyFields: [{ key: 'listcomp_numcorrect_urd', label: 'Number Correct' }],
  },
  letterid_urd: {
    label: 'Letter Identification (Urdu)',
    group: 'Urdu',
    items: Array.from({ length: 100 }, (_, i) => `letterid_fl_urd_${i + 1}`),
    summaryFields: [
      'lid_reading_correct_urd',
      'lid_reading_attempted_urd',
      'lid_reading_score_urd',
    ],
    verifyFields: [
      { key: 'lid_reading_correct_urd', label: 'Letters Correct' },
      { key: 'lid_reading_attempted_urd', label: 'Letters Attempted' },
    ],
  },
  idwrd_urd: {
    label: 'Word Reading (Urdu)',
    group: 'Urdu',
    items: Array.from({ length: 50 }, (_, i) => `idwrd_reading_urd_${i + 1}`),
    summaryFields: ['idwrd_60s_correct_urd', 'idwrd_60s_attempted_urd'],
    verifyFields: [
      { key: 'idwrd_60s_correct_urd', label: 'Words Correct (60s)' },
      { key: 'idwrd_60s_attempted_urd', label: 'Words Attempted (60s)' },
    ],
  },
  orf_urd: {
    label: 'Oral Reading Fluency (Urdu)',
    group: 'Urdu',
    items: Array.from({ length: 60 }, (_, i) => `orf_reading_urd_${i + 1}`),
    summaryFields: [
      'orf_60s_correct_urd',
      'orf_60s_attempted_urd',
      'orf_reading_sentences_urd',
    ],
    verifyFields: [
      { key: 'orf_60s_correct_urd', label: 'Words Correct (60s)' },
      { key: 'orf_60s_attempted_urd', label: 'Words Attempted (60s)' },
      { key: 'orf_reading_sentences_urd', label: 'Sentences Read' },
    ],
  },
  rdcomp_urd: {
    label: 'Reading Comprehension (Urdu)',
    group: 'Urdu',
    items: [
      'rdcomp_lit1_urd',
      'rdcomp_lit2_urd',
      'rdcomp_lit3_urd',
      'rdcomp_lit4_urd',
      'rdcomp_inf1_urd',
      'rdcomp_inf2_urd',
    ],
    summaryFields: ['rdcomp_numcorrect_urd', 'rdcomp_percorrect_urd'],
    verifyFields: [{ key: 'rdcomp_numcorrect_urd', label: 'Number Correct' }],
  },
  listcomp_eng: {
    label: 'Listening Comprehension (English)',
    group: 'English',
    items: [
      'listcomp_lit1_eng',
      'listcomp_lit2_eng',
      'listcomp_lit3_eng',
      'listcomp_lit4_eng',
      'listcomp_inf1_eng',
      'listcomp_inf2_eng',
    ],
    summaryFields: ['listcomp_numcorrect_eng', 'listcomp_percorrect_eng'],
    verifyFields: [{ key: 'listcomp_numcorrect_eng', label: 'Number Correct' }],
  },
  letterid_eng: {
    label: 'Letter Identification (English)',
    group: 'English',
    items: Array.from({ length: 100 }, (_, i) => `letterid_fl_eng_${i + 1}`),
    summaryFields: [
      'lid_reading_correct_eng',
      'lid_reading_attempted_eng',
      'lid_reading_score_eng',
    ],
    verifyFields: [
      { key: 'lid_reading_correct_eng', label: 'Letters Correct' },
      { key: 'lid_reading_attempted_eng', label: 'Letters Attempted' },
    ],
  },
  pw_eng: {
    label: 'Pseudoword Reading (English)',
    group: 'English',
    items: Array.from({ length: 50 }, (_, i) => `pw_reading_eng_${i + 1}`),
    summaryFields: ['pw_60s_correct_eng', 'pw_60s_attempted_eng'],
    verifyFields: [
      { key: 'pw_60s_correct_eng', label: 'Words Correct (60s)' },
      { key: 'pw_60s_attempted_eng', label: 'Words Attempted (60s)' },
    ],
  },
  idwrd_eng: {
    label: 'Word Reading (English)',
    group: 'English',
    items: Array.from({ length: 50 }, (_, i) => `idwrd_reading_eng_${i + 1}`),
    summaryFields: ['idwrd_60s_correct_eng', 'idwrd_60s_attempted_eng'],
    verifyFields: [
      { key: 'idwrd_60s_correct_eng', label: 'Words Correct (60s)' },
      { key: 'idwrd_60s_attempted_eng', label: 'Words Attempted (60s)' },
    ],
  },
  orf_eng: {
    label: 'Oral Reading Fluency (English)',
    group: 'English',
    items: Array.from({ length: 68 }, (_, i) => `orf_reading_eng_${i + 1}`),
    summaryFields: [
      'orf_60s_correct_eng',
      'orf_60s_attempted_eng',
      'orf_reading_sentences_eng',
    ],
    verifyFields: [
      { key: 'orf_60s_correct_eng', label: 'Words Correct (60s)' },
      { key: 'orf_60s_attempted_eng', label: 'Words Attempted (60s)' },
      { key: 'orf_reading_sentences_eng', label: 'Sentences Read' },
    ],
  },
  rdcomp_eng: {
    label: 'Reading Comprehension (English)',
    group: 'English',
    items: [
      'rdcomp_lit1_eng',
      'rdcomp_lit2_eng',
      'rdcomp_lit3_eng',
      'rdcomp_lit4_eng',
      'rdcomp_inf1_eng',
      'rdcomp_inf2_eng',
    ],
    summaryFields: ['rdcomp_numcorrect_eng', 'rdcomp_percorrect_eng'],
    verifyFields: [{ key: 'rdcomp_numcorrect_eng', label: 'Number Correct' }],
  },
  idnummag: {
    label: 'Number Identification',
    group: 'Math',
    items: [
      'identify_1a',
      'identify_1b',
      'identify_2a',
      'identify_2b',
      'identify_3a',
      'identify_3b',
      'identify_4a',
      'identify_4b',
    ],
    summaryFields: ['idnummag_numcorrect', 'idnummag_percorrect'],
    verifyFields: [{ key: 'idnummag_numcorrect', label: 'Number Correct' }],
  },
  numrep: {
    label: 'Number Representation',
    group: 'Math',
    items: [
      'represent_1a',
      'represent_1b',
      'represent_2a',
      'represent_2b',
      'represent_3a',
      'represent_3b',
      'represent_4a',
      'represent_4b',
    ],
    summaryFields: ['numrep_numcorrect', 'numrep_percorrect'],
    verifyFields: [{ key: 'numrep_numcorrect', label: 'Number Correct' }],
  },
  blfluency_l1: {
    label: 'Basic Letter Fluency (L1)',
    group: 'Math',
    items: Array.from({ length: 20 }, (_, i) => `blfl1_question_ans_${i + 1}`),
    summaryFields: ['blfl1_s1ore'],
    verifyFields: [{ key: 'blfl1_s1ore', label: 'Score' }],
  },
  blfluency_l4: {
    label: 'Basic Letter Fluency (L4)',
    group: 'Math',
    items: Array.from({ length: 20 }, (_, i) => `blfl4_question_ans_${i + 1}`),
    summaryFields: ['blfl4_s1ore'],
    verifyFields: [{ key: 'blfl4_s1ore', label: 'Score' }],
  },
  computation: {
    label: 'Computation',
    group: 'Math',
    items: [
      'computation_1a',
      'computation_1b',
      'computation_2a',
      'computation_2b',
      'computation_3a',
      'computation_3b',
      'computation_4a',
      'computation_4b',
    ],
    summaryFields: ['comp_numcorrect', 'comp_percorrect'],
    verifyFields: [{ key: 'comp_numcorrect', label: 'Number Correct' }],
  },
  word_problems: {
    label: 'Word Problems',
    group: 'Math',
    items: [
      'word_problems_1a',
      'word_problems_1b',
      'word_problems_2a',
      'word_problems_2b',
      'word_problems_3a',
      'word_problems_3b',
      'word_problems_4a',
      'word_problems_4b',
    ],
    summaryFields: ['wrdpblm_numcorrect', 'wrdpblm_percorrect'],
    verifyFields: [{ key: 'wrdpblm_numcorrect', label: 'Number Correct' }],
  },
  patterns: {
    label: 'Patterns',
    group: 'Math',
    items: [
      'patterns_1a',
      'patterns_1b',
      'patterns_2a',
      'patterns_2b',
      'patterns_3a',
      'patterns_3b',
      'patterns_4a',
      'patterns_4b',
    ],
    summaryFields: ['patterns_numcorrect', 'patterns_percorrect'],
    verifyFields: [{ key: 'patterns_numcorrect', label: 'Number Correct' }],
  },
};

module.exports = { SECTIONS };
